#page title
page_title                                : Newcomer Games                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

appstore_link                             : http://www.newcomer-tech.com/                                        # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
presskit_download_link                    : http://www.newcomer-tech.com/                                        # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 

app_icon                                  : # assets/N.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.

app_description                           : Defend your kingdom through effortless study. Free and playable on the web.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.


# Information About Yourself
your_name                                 : Newcomer Games                               
your_city                                 : the United States                                
email_address                             : newcomer.education.games@gmail.com
twitter_username                          : https://twitter.com/NewcomerGames


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Student Engagement
    description                           : Game-based learning increases learning engagement, motivation, and self-efficacy.
    fontawesome_icon_name                 : info-circle
    
  - title                                 : Dynamic Play
    description                           : Quests dynamically populated from study sets making it easy to study all the time. 
    fontawesome_icon_name                 : star
    
  - title                                 : Mobile Play
    description                           : Available on IOS and Android. Visit newcomer-tech.com on your mobile browser to play.
    fontawesome_icon_name                 : mobile



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
